- name: demo on variables
  hosts: all
  vars:
    URL: play.example.com
  tasks:
    - name: print URL
      ansible.builtin.debug:
        msg: URL - {{ URL }}

- name: demo on load variables from a file
  hosts: all
  vars_files:
    - exvars.yml
  tasks:
    - name: print URL
      ansible.builtin.debug:
        msg: URL - {{ URL }}
#vars_file does not support from task level

- name: demo on task level variables
  hosts: all
  tasks:
    - name: print URL
      ansible.builtin.debug:
        msg: URL - {{ URL }}
      vars:
        URL: play.example.com

- name: Variable from Roles
  hosts: all
  vars:
    URL_PLAY: play.example.com
  roles:
    - sample

- name: Demo on register variables
  hosts: all
  tasks:
    - name: Run uptime shell command
      ansible.builtin.shell: uptime
      register: output
    - name: Print output
      ansible.builtin.debug:
        msg: '{{ output.stdout }}'